[
  {statusId: 1, status: 'spacer', type: 1},
  {statusId: 2, status: 'spacer z psem', type: 1},
  {statusId: 3, status: 'wypad za miasto', type: 1},
  {statusId: 4, status: 'wakacje', type: 0},
  {statusId: 5, status: 'shopping', type: 0},
  {statusId: 6, status: 'plac zabaw z dziećmi', type: 1},
  {statusId: 7, status: 'kawa/herbata', type: 0},
  {statusId: 8, status: 'na piwo', type: 0},
  {statusId: 9, status: 'kino/teatr', type: 1},
  {statusId: 10, status: 'impreza', type: 0},
  {statusId: 11, status: 'osoba toważysząca na ślub', type: 0},
  {statusId: 12, status: 'grill', type: 0},
  {statusId: 13, status: 'kręgle', type: 0},
  {statusId: 14, status: 'bilard', type: 1},
  {statusId: 15, status: 'rower', type: 0},
  {statusId: 16, status: 'siłownia', type: 0},
  {statusId: 17, status: 'bieganie', type: 0},
  {statusId: 18, status: 'rolki', type: 0},
  {statusId: 19, status: 'basen', type: 1},
  {statusId: 20, status: 'piłka nożna', type: 0},
  {statusId: 21, status: 'narty/snowboard', type: 0},
  {statusId: 22, status: 'nordic walking', type: 0},
  {statusId: 23, status: 'lodowisko', type: 0},
  {statusId: 24, status: 'spadochron', type: 0},
  {statusId: 25, status: 'aquapark z dzieckiem', type: 1},
];
